name: PowerShell Validation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PowerShell Analysis
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path ./scripts -Recurse

          if ($results) {
              $results | Format-Table
              throw "PSScriptAnalyzer detected issues."
          }
